# Generated by Django 3.0.7 on 2020-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_song_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
