# Generated by Django 3.0.7 on 2020-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_song_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
